---
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest

    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest

    - name: Install lvm2
      yum:
        name: lvm2
        state: latest

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes

    - name: Install pip
      package: name=python-pip state=present
    - name: install docker-py package
      pip: name=docker-py

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create directory for Docker Playbook
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /var/lib/jenkins/workspace/frontend_job
        - /var/lib/jenkins/workspace/backend_job

    - name: Copy Ansible Playbook to workspace of frontend (Jenkins)
      template:
        src: /home/vagrant/templates/frontend.yml
        dest: /var/lib/jenkins/workspace/frontend_job

    - name: Copy DockerFile to workspace of frontend (Jenkins)
      template:
        src: /home/vagrant/templates/Dockerfile_frontend
        dest: /var/lib/jenkins/workspace/frontend_job/Dockerfile
    
    - name: Copy Ansible Playbook to workspace of backend (Jenkins)
      template:
        src: /home/vagrant/templates/backend.yml
        dest: /var/lib/jenkins/workspace/backend_job

    - name: Copy DockerFile to workspace of backend (Jenkins)
      template:
        src: /home/vagrant/templates/Dockerfile_backend
        dest: /var/lib/jenkins/workspace/backend_job/Dockerfile        

    - name: Read Jankins admin password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: adminpwd

    - name: Create backend_job from xml-file
      jenkins_job:
        config: "{{ lookup('file', '/home/vagrant/templates/backend_job.xml') }}"
        name: backend_job
        password: "{{ adminpwd.stdout }}" 
        url: http://localhost:8080
        user: "admin"
    

    - name: Create fronend_job from xml-file
      jenkins_job:
        config: "{{ lookup('file', '/home/vagrant/templates/frontend_job.xml') }}"
        name: frontend_job
        password: "{{ adminpwd.stdout }}" 
        url: http://localhost:8080
        user: "admin"

    - name: Build job_backend
      shell: "java -jar /var/cache/jenkins/war/WEB-INF/jenkins-cli.jar -s http://localhost:8080/ -auth admin:{{ adminpwd.stdout }} build backend_job"

    - name: Build job_frontend
      shell: "java -jar /var/cache/jenkins/war/WEB-INF/jenkins-cli.jar -s http://localhost:8080/ -auth admin:{{ adminpwd.stdout }} build frontend_job"
...